# sd card PINS OUT 
SDCARD_PIN_CS   = 13   # any free pin
SDCARD_PIN_CLK  = 14   # SPI1 SCK
SDCARD_PIN_MOSI = 15   # SPI1 TX
SDCARD_PIN_MISO = 12   # SPI1 RX
 
# Mic PINS OUT 
MIC_PIN_SCK = 16
MIC_PIN_WS = 17
MIC_PIN_SD = 18

# OLED PINS OUT 
OLED_PIN_SDA = 10
OLED_PIN_SCL = 11

# Speaker Amplifier PINS OUT
SPEAKER_AMP_PIN_SCK = 2 # BCLK
SPEAKER_AMP_PIN_WS = 3  # LRCK  
SPEAKER_AMP_PIN_SD = 4  # DIN to amplifier

# Nrf radio module
NRF_PIN_SCK = 6
NRF_PIN_MISO = 0
NRF_PIN_MOSI = 7
NRF_PIN_CE = 1
NRF_PIN_CSN = 5

# record button
LED_PIN_REC_BTN = 20
SWITCH_PIN_REC_BTN = 21