# sd card PINS OUT 
PIN_SDCARD_CS   = 13   # any free pin
PIN_SDCARD_CLK  = 14   # SPI1 SCK
PIN_SDCARD_MOSI = 15   # SPI1 TX
PIN_SDCARD_MISO = 12   # SPI1 RX
 
# Mic PINS OUT 
PIN_MIC_SCK = 16
PIN_MIC_WS = 17
PIN_MIC_SD = 18

# OLED PINS OUT 
PIN_OLED_SDA = 10
PIN_OLED_SCL = 11

# Speaker Amplifier PINS OUT
PIN_SPEAKER_AMP_SCK = 2 # BCLK
PIN_SPEAKER_AMP_WS = 3  # LRCK  
PIN_SPEAKER_AMP_SD = 4  # DIN to amplifier

# Nrf radio module
PIN_NRF_SCK = 6
PIN_NRF_MISO = 0
PIN_NRF_MOSI = 7
PIN_NRF_CE = 1
PIN_NRF_CSN = 5

# ENCOUDER BTN
PIN_ENC_A = 26 # right
PIN_ENC_B = 27 # left
PIN_BTN_HOME = 19

# Record BTN
PIN_REC_LED = 9
PIN_REC_BTN = 20

# BTNS
PIN_BTN_AGREE = 21
PIN_BTN_CANCEL = 22
