// -------------------------------------------------------------- //
// This file is autogenerated by pioasm version 1.0; do not edit! //
// -------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// sdcard //
// ------ //

#define sdcard_wrap_target 0
#define sdcard_wrap 5
#define sdcard_pio_version 0

#define sdcard_offset_entry_point 0u

static const uint16_t sdcard_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0
    0xe027, //  1: set    x, 7            side 0
    0x6101, //  2: out    pins, 1         side 0 [1]
    0x5101, //  3: in     pins, 1         side 1 [1]
    0x0042, //  4: jmp    x--, 2          side 0
    0x8020, //  5: push   block           side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sdcard_program = {
    .instructions = sdcard_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = sdcard_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config sdcard_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sdcard_wrap_target, offset + sdcard_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

